# Change these first
owner: Zero-wyc #您的GitHub组织或用户名（此存储库所在的位置）
repo: upptime # 此存储库的名称

sites:
  - name: Zero251.xyz
    url: https://Zero251.xyz
  - name: blog.Zero251.xyz
    url: https://blog.Zero251.xyz
  - name: typing.Zero251.xyz
    url: https://typing.Zero251.xyz
  - name: p.zero251.xyz
    url: https://p.zero251.xyz
  - name: openlist.dx.Zero251.xyz
    url: http://openlist.Zero251.xyz
  - name: openlist.Zero251.xyz


status-website:
  # 添加您的自定义域名，或者如果您没有域名，请删除 `cname` 行
  # 如果您没有自定义域名，请取消注释 `baseUrl` 行并添加您的仓库名称
  cname: upptime.zero251.xyz
  # baseUrl: /your-repo-name
  logoUrl: https://p.zero251.xyz/i/2025/03/28/甘城.svg
  favicon: https://cdn.jsdelivr.net/gh/Zero-wyc/Image@main/myself/20251123130802738.png
  name: Upptime-网站运行状态面板
  introTitle: 由 GitHub 提供支持。"
  introMessage: "来主页看看捏[Zero251.xyz](https://Zero251.xyz)"
  navbar:
    - title: 状态
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime 还支持通知、指派 issues（问题）等更多功能
# 参见 https://upptime.js.org/docs/configuration
